// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package emailproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientMessage struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//	*ClientMessage_AckResponse
	//	*ClientMessage_NoopRequest
	//	*ClientMessage_StartupRequest
	//	*ClientMessage_ErrorResponse
	//	*ClientMessage_GetAccountsRequest
	//	*ClientMessage_GetSnapshotsRequest
	MessageType          isClientMessage_MessageType `protobuf_oneof:"message_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isClientMessage_MessageType interface {
	isClientMessage_MessageType()
}

type ClientMessage_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,2,opt,name=ack_response,json=ackResponse,proto3,oneof"`
}

type ClientMessage_NoopRequest struct {
	NoopRequest *NoopRequest `protobuf:"bytes,3,opt,name=noop_request,json=noopRequest,proto3,oneof"`
}

type ClientMessage_StartupRequest struct {
	StartupRequest *StartupRequest `protobuf:"bytes,4,opt,name=startup_request,json=startupRequest,proto3,oneof"`
}

type ClientMessage_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,5,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type ClientMessage_GetAccountsRequest struct {
	GetAccountsRequest *GetAccountsRequest `protobuf:"bytes,6,opt,name=get_accounts_request,json=getAccountsRequest,proto3,oneof"`
}

type ClientMessage_GetSnapshotsRequest struct {
	GetSnapshotsRequest *GetSnapshotsRequest `protobuf:"bytes,7,opt,name=get_snapshots_request,json=getSnapshotsRequest,proto3,oneof"`
}

func (*ClientMessage_AckResponse) isClientMessage_MessageType() {}

func (*ClientMessage_NoopRequest) isClientMessage_MessageType() {}

func (*ClientMessage_StartupRequest) isClientMessage_MessageType() {}

func (*ClientMessage_ErrorResponse) isClientMessage_MessageType() {}

func (*ClientMessage_GetAccountsRequest) isClientMessage_MessageType() {}

func (*ClientMessage_GetSnapshotsRequest) isClientMessage_MessageType() {}

func (m *ClientMessage) GetMessageType() isClientMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *ClientMessage) GetAckResponse() *AckResponse {
	if x, ok := m.GetMessageType().(*ClientMessage_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (m *ClientMessage) GetNoopRequest() *NoopRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_NoopRequest); ok {
		return x.NoopRequest
	}
	return nil
}

func (m *ClientMessage) GetStartupRequest() *StartupRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_StartupRequest); ok {
		return x.StartupRequest
	}
	return nil
}

func (m *ClientMessage) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*ClientMessage_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *ClientMessage) GetGetAccountsRequest() *GetAccountsRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_GetAccountsRequest); ok {
		return x.GetAccountsRequest
	}
	return nil
}

func (m *ClientMessage) GetGetSnapshotsRequest() *GetSnapshotsRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_GetSnapshotsRequest); ok {
		return x.GetSnapshotsRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientMessage_AckResponse)(nil),
		(*ClientMessage_NoopRequest)(nil),
		(*ClientMessage_StartupRequest)(nil),
		(*ClientMessage_ErrorResponse)(nil),
		(*ClientMessage_GetAccountsRequest)(nil),
		(*ClientMessage_GetSnapshotsRequest)(nil),
	}
}

type ServerMessage struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//	*ServerMessage_AckResponse
	//	*ServerMessage_NoopRequest
	//	*ServerMessage_ErrorResponse
	//	*ServerMessage_ClaimRequest
	//	*ServerMessage_ConfigChangedRequest
	//	*ServerMessage_StartupResponse
	//	*ServerMessage_GetAccountsResponse
	//	*ServerMessage_GetSnapshotsResponse
	MessageType          isServerMessage_MessageType `protobuf_oneof:"message_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{1}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isServerMessage_MessageType interface {
	isServerMessage_MessageType()
}

type ServerMessage_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,2,opt,name=ack_response,json=ackResponse,proto3,oneof"`
}

type ServerMessage_NoopRequest struct {
	NoopRequest *NoopRequest `protobuf:"bytes,3,opt,name=noop_request,json=noopRequest,proto3,oneof"`
}

type ServerMessage_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,4,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type ServerMessage_ClaimRequest struct {
	ClaimRequest *ClaimRequest `protobuf:"bytes,5,opt,name=claim_request,json=claimRequest,proto3,oneof"`
}

type ServerMessage_ConfigChangedRequest struct {
	ConfigChangedRequest *ConfigChangedRequest `protobuf:"bytes,6,opt,name=config_changed_request,json=configChangedRequest,proto3,oneof"`
}

type ServerMessage_StartupResponse struct {
	StartupResponse *StartupResponse `protobuf:"bytes,7,opt,name=startup_response,json=startupResponse,proto3,oneof"`
}

type ServerMessage_GetAccountsResponse struct {
	GetAccountsResponse *GetAccountsResponse `protobuf:"bytes,8,opt,name=get_accounts_response,json=getAccountsResponse,proto3,oneof"`
}

type ServerMessage_GetSnapshotsResponse struct {
	GetSnapshotsResponse *GetSnapshotsResponse `protobuf:"bytes,9,opt,name=get_snapshots_response,json=getSnapshotsResponse,proto3,oneof"`
}

func (*ServerMessage_AckResponse) isServerMessage_MessageType() {}

func (*ServerMessage_NoopRequest) isServerMessage_MessageType() {}

func (*ServerMessage_ErrorResponse) isServerMessage_MessageType() {}

func (*ServerMessage_ClaimRequest) isServerMessage_MessageType() {}

func (*ServerMessage_ConfigChangedRequest) isServerMessage_MessageType() {}

func (*ServerMessage_StartupResponse) isServerMessage_MessageType() {}

func (*ServerMessage_GetAccountsResponse) isServerMessage_MessageType() {}

func (*ServerMessage_GetSnapshotsResponse) isServerMessage_MessageType() {}

func (m *ServerMessage) GetMessageType() isServerMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *ServerMessage) GetAckResponse() *AckResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (m *ServerMessage) GetNoopRequest() *NoopRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_NoopRequest); ok {
		return x.NoopRequest
	}
	return nil
}

func (m *ServerMessage) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *ServerMessage) GetClaimRequest() *ClaimRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_ClaimRequest); ok {
		return x.ClaimRequest
	}
	return nil
}

func (m *ServerMessage) GetConfigChangedRequest() *ConfigChangedRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_ConfigChangedRequest); ok {
		return x.ConfigChangedRequest
	}
	return nil
}

func (m *ServerMessage) GetStartupResponse() *StartupResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_StartupResponse); ok {
		return x.StartupResponse
	}
	return nil
}

func (m *ServerMessage) GetGetAccountsResponse() *GetAccountsResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_GetAccountsResponse); ok {
		return x.GetAccountsResponse
	}
	return nil
}

func (m *ServerMessage) GetGetSnapshotsResponse() *GetSnapshotsResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_GetSnapshotsResponse); ok {
		return x.GetSnapshotsResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerMessage_AckResponse)(nil),
		(*ServerMessage_NoopRequest)(nil),
		(*ServerMessage_ErrorResponse)(nil),
		(*ServerMessage_ClaimRequest)(nil),
		(*ServerMessage_ConfigChangedRequest)(nil),
		(*ServerMessage_StartupResponse)(nil),
		(*ServerMessage_GetAccountsResponse)(nil),
		(*ServerMessage_GetSnapshotsResponse)(nil),
	}
}

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceInstanceId    string   `protobuf:"bytes,2,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	First                string   `protobuf:"bytes,5,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,6,opt,name=last,proto3" json:"last,omitempty"`
	DisplayName          string   `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Password             []byte   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetServiceInstanceId() string {
	if m != nil {
		return m.ServiceInstanceId
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *Account) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *Account) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Account) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type AckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckResponse) Reset()         { *m = AckResponse{} }
func (m *AckResponse) String() string { return proto.CompactTextString(m) }
func (*AckResponse) ProtoMessage()    {}
func (*AckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{3}
}

func (m *AckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckResponse.Unmarshal(m, b)
}
func (m *AckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckResponse.Marshal(b, m, deterministic)
}
func (m *AckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckResponse.Merge(m, src)
}
func (m *AckResponse) XXX_Size() int {
	return xxx_messageInfo_AckResponse.Size(m)
}
func (m *AckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckResponse proto.InternalMessageInfo

type ClaimRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimRequest) Reset()         { *m = ClaimRequest{} }
func (m *ClaimRequest) String() string { return proto.CompactTextString(m) }
func (*ClaimRequest) ProtoMessage()    {}
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{4}
}

func (m *ClaimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimRequest.Unmarshal(m, b)
}
func (m *ClaimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimRequest.Marshal(b, m, deterministic)
}
func (m *ClaimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimRequest.Merge(m, src)
}
func (m *ClaimRequest) XXX_Size() int {
	return xxx_messageInfo_ClaimRequest.Size(m)
}
func (m *ClaimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimRequest proto.InternalMessageInfo

func (m *ClaimRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConfigChangedRequest struct {
	HashesByTable        map[string][]byte `protobuf:"bytes,1,rep,name=hashes_by_table,json=hashesByTable,proto3" json:"hashes_by_table,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfigChangedRequest) Reset()         { *m = ConfigChangedRequest{} }
func (m *ConfigChangedRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigChangedRequest) ProtoMessage()    {}
func (*ConfigChangedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{5}
}

func (m *ConfigChangedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigChangedRequest.Unmarshal(m, b)
}
func (m *ConfigChangedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigChangedRequest.Marshal(b, m, deterministic)
}
func (m *ConfigChangedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigChangedRequest.Merge(m, src)
}
func (m *ConfigChangedRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigChangedRequest.Size(m)
}
func (m *ConfigChangedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigChangedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigChangedRequest proto.InternalMessageInfo

func (m *ConfigChangedRequest) GetHashesByTable() map[string][]byte {
	if m != nil {
		return m.HashesByTable
	}
	return nil
}

type ErrorResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{6}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{7}
}

func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(m, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

type GetAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{8}
}

func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(m, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetSnapshotsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSnapshotsRequest) Reset()         { *m = GetSnapshotsRequest{} }
func (m *GetSnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotsRequest) ProtoMessage()    {}
func (*GetSnapshotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{9}
}

func (m *GetSnapshotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotsRequest.Unmarshal(m, b)
}
func (m *GetSnapshotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotsRequest.Marshal(b, m, deterministic)
}
func (m *GetSnapshotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotsRequest.Merge(m, src)
}
func (m *GetSnapshotsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotsRequest.Size(m)
}
func (m *GetSnapshotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotsRequest proto.InternalMessageInfo

type GetSnapshotsResponse struct {
	Snapshots            []*Snapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetSnapshotsResponse) Reset()         { *m = GetSnapshotsResponse{} }
func (m *GetSnapshotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotsResponse) ProtoMessage()    {}
func (*GetSnapshotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{10}
}

func (m *GetSnapshotsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotsResponse.Unmarshal(m, b)
}
func (m *GetSnapshotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotsResponse.Marshal(b, m, deterministic)
}
func (m *GetSnapshotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotsResponse.Merge(m, src)
}
func (m *GetSnapshotsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotsResponse.Size(m)
}
func (m *GetSnapshotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotsResponse proto.InternalMessageInfo

func (m *GetSnapshotsResponse) GetSnapshots() []*Snapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type NoopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoopRequest) Reset()         { *m = NoopRequest{} }
func (m *NoopRequest) String() string { return proto.CompactTextString(m) }
func (*NoopRequest) ProtoMessage()    {}
func (*NoopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{11}
}

func (m *NoopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoopRequest.Unmarshal(m, b)
}
func (m *NoopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoopRequest.Marshal(b, m, deterministic)
}
func (m *NoopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoopRequest.Merge(m, src)
}
func (m *NoopRequest) XXX_Size() int {
	return xxx_messageInfo_NoopRequest.Size(m)
}
func (m *NoopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoopRequest proto.InternalMessageInfo

type Snapshot struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{12}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Snapshot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StartupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartupRequest) Reset()         { *m = StartupRequest{} }
func (m *StartupRequest) String() string { return proto.CompactTextString(m) }
func (*StartupRequest) ProtoMessage()    {}
func (*StartupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{13}
}

func (m *StartupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupRequest.Unmarshal(m, b)
}
func (m *StartupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupRequest.Marshal(b, m, deterministic)
}
func (m *StartupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupRequest.Merge(m, src)
}
func (m *StartupRequest) XXX_Size() int {
	return xxx_messageInfo_StartupRequest.Size(m)
}
func (m *StartupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartupRequest proto.InternalMessageInfo

type StartupResponse struct {
	ConfigHashesByTable  map[string][]byte `protobuf:"bytes,1,rep,name=config_hashes_by_table,json=configHashesByTable,proto3" json:"config_hashes_by_table,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StartupResponse) Reset()         { *m = StartupResponse{} }
func (m *StartupResponse) String() string { return proto.CompactTextString(m) }
func (*StartupResponse) ProtoMessage()    {}
func (*StartupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{14}
}

func (m *StartupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupResponse.Unmarshal(m, b)
}
func (m *StartupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupResponse.Marshal(b, m, deterministic)
}
func (m *StartupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupResponse.Merge(m, src)
}
func (m *StartupResponse) XXX_Size() int {
	return xxx_messageInfo_StartupResponse.Size(m)
}
func (m *StartupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartupResponse proto.InternalMessageInfo

func (m *StartupResponse) GetConfigHashesByTable() map[string][]byte {
	if m != nil {
		return m.ConfigHashesByTable
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientMessage)(nil), "emailproto.ClientMessage")
	proto.RegisterType((*ServerMessage)(nil), "emailproto.ServerMessage")
	proto.RegisterType((*Account)(nil), "emailproto.Account")
	proto.RegisterType((*AckResponse)(nil), "emailproto.AckResponse")
	proto.RegisterType((*ClaimRequest)(nil), "emailproto.ClaimRequest")
	proto.RegisterType((*ConfigChangedRequest)(nil), "emailproto.ConfigChangedRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "emailproto.ConfigChangedRequest.HashesByTableEntry")
	proto.RegisterType((*ErrorResponse)(nil), "emailproto.ErrorResponse")
	proto.RegisterType((*GetAccountsRequest)(nil), "emailproto.GetAccountsRequest")
	proto.RegisterType((*GetAccountsResponse)(nil), "emailproto.GetAccountsResponse")
	proto.RegisterType((*GetSnapshotsRequest)(nil), "emailproto.GetSnapshotsRequest")
	proto.RegisterType((*GetSnapshotsResponse)(nil), "emailproto.GetSnapshotsResponse")
	proto.RegisterType((*NoopRequest)(nil), "emailproto.NoopRequest")
	proto.RegisterType((*Snapshot)(nil), "emailproto.Snapshot")
	proto.RegisterType((*StartupRequest)(nil), "emailproto.StartupRequest")
	proto.RegisterType((*StartupResponse)(nil), "emailproto.StartupResponse")
	proto.RegisterMapType((map[string][]byte)(nil), "emailproto.StartupResponse.ConfigHashesByTableEntry")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xc7, 0xaf, 0x93, 0xb4, 0x8d, 0x4f, 0xbe, 0x7a, 0x27, 0xee, 0xbd, 0xb9, 0xb9, 0x12, 0x04,
	0x0b, 0xa4, 0xae, 0x82, 0xd4, 0xb2, 0x40, 0x08, 0x09, 0xda, 0xaa, 0xa5, 0x45, 0xa2, 0x8b, 0x29,
	0x48, 0x48, 0x2c, 0xac, 0xa9, 0x3d, 0x75, 0xac, 0x38, 0xb6, 0xf1, 0x38, 0x45, 0x79, 0x00, 0x1e,
	0x89, 0x37, 0xe0, 0x31, 0xd8, 0xf0, 0x26, 0x68, 0xc6, 0x13, 0xcf, 0x38, 0x36, 0xa0, 0xee, 0xd8,
	0xcd, 0xf9, 0x98, 0xbf, 0xcf, 0xc9, 0xf9, 0xcd, 0x09, 0x74, 0xe8, 0x82, 0x04, 0xe1, 0x34, 0x49,
	0xe3, 0x2c, 0x46, 0x20, 0x0c, 0x71, 0xb6, 0xbf, 0x37, 0xa1, 0x77, 0x12, 0x06, 0x34, 0xca, 0xde,
	0x50, 0xc6, 0x88, 0x4f, 0x51, 0x1f, 0x1a, 0x81, 0x37, 0x32, 0x26, 0xc6, 0x7e, 0x0b, 0x37, 0x02,
	0x0f, 0x3d, 0x87, 0x2e, 0x71, 0xe7, 0x4e, 0x4a, 0x59, 0x12, 0x47, 0x8c, 0x8e, 0x1a, 0x13, 0x63,
	0xbf, 0x73, 0xf0, 0xef, 0x54, 0x89, 0x4c, 0x8f, 0xdc, 0x39, 0x96, 0xe1, 0xf3, 0xbf, 0x70, 0x87,
	0x28, 0x93, 0xdf, 0x8e, 0xe2, 0x38, 0x71, 0x52, 0xfa, 0x71, 0x49, 0x59, 0x36, 0x6a, 0x56, 0x6f,
	0x5f, 0xc6, 0x71, 0x82, 0xf3, 0x30, 0xbf, 0x1d, 0x29, 0x13, 0x9d, 0xc2, 0x80, 0x65, 0x24, 0xcd,
	0x96, 0x4a, 0xa0, 0x25, 0x04, 0xc6, 0xba, 0xc0, 0x55, 0x9e, 0xa2, 0x34, 0xfa, 0xac, 0xe4, 0x41,
	0xc7, 0xd0, 0xa7, 0x69, 0x1a, 0xa7, 0xaa, 0x89, 0x2d, 0xa1, 0xf2, 0x9f, 0xae, 0x72, 0xca, 0x33,
	0xb4, 0x36, 0x7a, 0x54, 0x77, 0x20, 0x0c, 0x96, 0x4f, 0x33, 0x87, 0xb8, 0x6e, 0xbc, 0x8c, 0x32,
	0x56, 0xd4, 0xb3, 0x2d, 0x94, 0xee, 0xe9, 0x4a, 0xaf, 0x68, 0x76, 0x24, 0xd3, 0x54, 0x4d, 0xc8,
	0xaf, 0x78, 0xd1, 0x3b, 0xd8, 0xe3, 0x9a, 0x2c, 0x22, 0x09, 0x9b, 0xc5, 0x9a, 0xe8, 0x8e, 0x10,
	0xbd, 0xbf, 0x21, 0x7a, 0xb5, 0xce, 0x53, 0xaa, 0x43, 0xbf, 0xea, 0x3e, 0xee, 0x43, 0x77, 0x91,
	0x0f, 0xd3, 0xc9, 0x56, 0x09, 0xb5, 0x3f, 0x6f, 0x41, 0xef, 0x8a, 0xa6, 0xb7, 0x34, 0xfd, 0x13,
	0x67, 0x5c, 0x1d, 0x4e, 0xeb, 0xce, 0xc3, 0x79, 0x01, 0x3d, 0x37, 0x24, 0xc1, 0xa2, 0x28, 0x21,
	0x9f, 0xef, 0x48, 0x97, 0x38, 0xe1, 0x09, 0xaa, 0x86, 0xae, 0xab, 0xd9, 0xe8, 0x3d, 0xfc, 0xe3,
	0xc6, 0xd1, 0x4d, 0xe0, 0x3b, 0xee, 0x8c, 0x44, 0x3e, 0xf5, 0x36, 0xe6, 0x3b, 0x29, 0x29, 0x89,
	0xcc, 0x93, 0x3c, 0x51, 0x29, 0x5a, 0x6e, 0x8d, 0x1f, 0x9d, 0xc3, 0xae, 0x42, 0x58, 0x36, 0x98,
	0x8f, 0xf7, 0xff, 0x5a, 0x86, 0x8b, 0x16, 0x07, 0xac, 0xec, 0x5a, 0xd3, 0xa2, 0x11, 0x28, 0xe5,
	0xda, 0xb5, 0xb4, 0x28, 0xd8, 0x0a, 0xc9, 0xa1, 0x5f, 0x75, 0xf3, 0xd6, 0x37, 0x21, 0x94, 0xba,
	0x66, 0xb5, 0xf5, 0x32, 0x85, 0x85, 0xb0, 0xe5, 0xd7, 0xf8, 0x2b, 0x1c, 0x7e, 0x33, 0x60, 0x47,
	0x7e, 0x5e, 0x23, 0xd0, 0x14, 0x04, 0x4e, 0x61, 0xc8, 0x68, 0x7a, 0x1b, 0xb8, 0xd4, 0x09, 0x22,
	0x96, 0x91, 0x88, 0x1f, 0x3c, 0x01, 0xa2, 0x89, 0xff, 0x96, 0xa1, 0x0b, 0x19, 0xb9, 0xf0, 0x10,
	0x82, 0x56, 0x44, 0x16, 0x54, 0xb0, 0x66, 0x62, 0x71, 0x46, 0x16, 0x6c, 0x89, 0x52, 0x05, 0x40,
	0x26, 0xce, 0x0d, 0xee, 0xbd, 0x09, 0x52, 0xc9, 0x84, 0x89, 0x73, 0x83, 0xdf, 0x0f, 0x89, 0x1c,
	0xaf, 0x89, 0xc5, 0x19, 0x3d, 0x80, 0xae, 0x17, 0xb0, 0x24, 0x24, 0x2b, 0x47, 0x68, 0xef, 0x88,
	0x58, 0x47, 0xfa, 0x2e, 0xf9, 0x27, 0xc6, 0xd0, 0x4e, 0x08, 0x63, 0x9f, 0xe2, 0xd4, 0x13, 0x3f,
	0x7b, 0x17, 0x17, 0xb6, 0xdd, 0x83, 0x8e, 0xf6, 0x48, 0xec, 0x87, 0xd0, 0xd5, 0x91, 0xe3, 0x75,
	0x64, 0xf1, 0x9c, 0x46, 0xb2, 0xe9, 0xdc, 0xb0, 0xbf, 0x18, 0x60, 0xd5, 0xf1, 0x84, 0x3e, 0xc0,
	0x60, 0x46, 0xd8, 0x8c, 0x32, 0xe7, 0x7a, 0xe5, 0x64, 0xe4, 0x3a, 0xa4, 0x23, 0x63, 0xd2, 0xdc,
	0xef, 0x1c, 0x1c, 0xfe, 0x0e, 0xc5, 0xe9, 0xb9, 0xb8, 0x77, 0xbc, 0x7a, 0xcb, 0x6f, 0x9d, 0x46,
	0x59, 0xba, 0xc2, 0xbd, 0x99, 0xee, 0x1b, 0xbf, 0x04, 0x54, 0x4d, 0x42, 0xbb, 0xd0, 0x9c, 0xd3,
	0x95, 0xac, 0x8f, 0x1f, 0x79, 0xcd, 0xb7, 0x24, 0x5c, 0xe6, 0x0b, 0xa1, 0x8b, 0x73, 0xe3, 0x59,
	0xe3, 0xa9, 0x61, 0x3f, 0x82, 0x5e, 0xe9, 0x4d, 0x8a, 0x1f, 0x9f, 0x3b, 0xd6, 0xed, 0x09, 0xc3,
	0xb6, 0x00, 0x55, 0xb7, 0xa1, 0x7d, 0x06, 0xc3, 0x1a, 0x40, 0xd1, 0x63, 0x68, 0xaf, 0xe1, 0x96,
	0xbd, 0x0e, 0xcb, 0x1b, 0x48, 0xc4, 0x70, 0x91, 0x64, 0xef, 0x09, 0x9d, 0xcd, 0xfd, 0x67, 0xbf,
	0x06, 0xab, 0x8e, 0x53, 0x74, 0x00, 0x66, 0x41, 0xb9, 0xfc, 0x80, 0x55, 0x7a, 0x83, 0x32, 0x88,
	0x55, 0x1a, 0x1f, 0xaa, 0xb6, 0xbb, 0xec, 0x29, 0xb4, 0xd7, 0x59, 0x15, 0x84, 0xd7, 0x48, 0x36,
	0x14, 0x92, 0xf6, 0x2e, 0xf4, 0xcb, 0xff, 0x4e, 0xf6, 0x57, 0x03, 0x06, 0x1b, 0x8f, 0x1d, 0x05,
	0xc5, 0xf6, 0xa9, 0x1f, 0xf9, 0x93, 0x5f, 0x6c, 0x0a, 0x89, 0x40, 0xcd, 0xcc, 0x87, 0x6e, 0x35,
	0x32, 0x3e, 0x83, 0xd1, 0xcf, 0x2e, 0xdc, 0x65, 0xfe, 0xd7, 0xdb, 0xa2, 0x98, 0xc3, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xf3, 0xa9, 0x1b, 0xfa, 0x59, 0x08, 0x00, 0x00,
}
